-- --------------------------------------------------------------------------------------------------------------------
--
-- Insert em usuários
--
-- --------------------------------------------------------------------------------------------------------------------
INSERT INTO usuarios (usu_cod, usu_nome, usu_email, usu_senha, usu_acesso) 
VALUES (NULL, 'Marcelo', 'marcelo.jordao@etec.sp.gov.br', MD5('admin'), DEFAULT);

INSERT INTO usuarios (usu_cod, usu_nome, usu_email, usu_senha, usu_acesso) 
VALUES (NULL, 'Roberto', 'roberto@etec.sp.gov.br', MD5('admin'), DEFAULT);

INSERT INTO usuarios (usu_cod, usu_nome, usu_email, usu_senha, usu_acesso) 
VALUES (NULL, 'Leonardo', 'marcelo.jordao@etec.sp.gov.br', MD5('admin'), DEFAULT);

INSERT INTO usuarios (usu_cod, usu_nome, usu_email, usu_senha, usu_acesso) 
VALUES (NULL, 'Igor', 'marcelo.jordao@etec.sp.gov.br', MD5('admin'), DEFAULT);

INSERT INTO usuarios (usu_cod, usu_nome, usu_email, usu_senha, usu_acesso) 
VALUES (NULL, 'Vinicius', 'marcelo.jordao@etec.sp.gov.br', MD5('admin'), DEFAULT);

SELECT * FROM usuarios;

-- --------------------------------------------------------------------------------------------------------------------
--
-- Insert em avaliacoes
--
-- --------------------------------------------------------------------------------------------------------------------
INSERT INTO avaliacoes (ava_pergcod, ava_like, ava_dislike) VALUES (1, 2, 3);

INSERT INTO avaliacoes (ava_pergcod, ava_like, ava_dislike) VALUES (3, 2, 1);

INSERT INTO avaliacoes (ava_pergcod, ava_like, ava_dislike) VALUES (2, 1, 3);

INSERT INTO avaliacoes (ava_pergcod, ava_like, ava_dislike) VALUES (2, 3, 1);

INSERT INTO avaliacoes (ava_pergcod, ava_like, ava_dislike) VALUES (3, 1, 2);

SELECT * FROM avaliacoes;

-- --------------------------------------------------------------------------------------------------------------------
--
-- Insert em respostas
--
-- --------------------------------------------------------------------------------------------------------------------
INSERT INTO respostas (resp_cod, resp_conteudo, resp_resposta, resp_pergcod) 
VALUES (NULL, '', 0, 1);

INSERT INTO respostas (resp_cod, resp_conteudo, resp_resposta, resp_pergcod) 
VALUES (NULL, '', 0, 1);

INSERT INTO respostas (resp_cod, resp_conteudo, resp_resposta, resp_pergcod) 
VALUES (NULL, '', 0, 1);

INSERT INTO respostas (resp_cod, resp_conteudo, resp_resposta, resp_pergcod) 
VALUES (NULL, '', 0, 1);

INSERT INTO respostas (resp_cod, resp_conteudo, resp_resposta, resp_pergcod) 
VALUES (NULL, '', 0, 1);

SELECT * FROM respostas;

-- --------------------------------------------------------------------------------------------------------------------
--
-- Insert em respostas
--
-- --------------------------------------------------------------------------------------------------------------------
INSERT INTO perguntas (perg_cod, perg_ano, perg_vestibular, perg_materia, perg_conteudo, perg_data, perg_usuario) 
VALUES (NULL, '2001', 'UNESP', 'Matemática', 'Eu sou bom em PHP', '2001-05-07', 1);

INSERT INTO perguntas (perg_cod, perg_ano, perg_vestibular, perg_materia, perg_conteudo, perg_data, perg_usuario) 
VALUES (NULL, '2001', 'UNESP', 'Matemática', 'Eu sou bom em PHP', '2001-05-07', 1);

INSERT INTO perguntas (perg_cod, perg_ano, perg_vestibular, perg_materia, perg_conteudo, perg_data, perg_usuario) 
VALUES (NULL, '2001', 'UNESP', 'Matemática', 'Eu sou bom em PHP', '2001-05-07', 1);

INSERT INTO perguntas (perg_cod, perg_ano, perg_vestibular, perg_materia, perg_conteudo, perg_data, perg_usuario) 
VALUES (NULL, '2001', 'UNESP', 'Matemática', 'Eu sou bom em PHP', '2001-05-07', 1);

INSERT INTO perguntas (perg_cod, perg_ano, perg_vestibular, perg_materia, perg_conteudo, perg_data, perg_usuario) 
VALUES (NULL, '2001', 'UNESP', 'Matemática', 'Eu sou bom em PHP', '2001-05-07', 1);

SELECT * FROM perguntas;

-- --------------------------------------------------------------------------------------------------------------------
--
-- Insert em perguntas
--
-- --------------------------------------------------------------------------------------------------------------------
INSERT INTO `perguntas` (`perg_cod`, `perg_ano`, `perg_vestibular`, `perg_materia`, `perg_conteudo`, `perg_data`, `perg_usuario`, `perg_alternativacorreta`) VALUES
(NULL, 2015, 'vesti-lar', 'Língua Portuguesa ', 'Garcia tinha-se chegado ao cadáver, levantara o lenço e contemplara por alguns instantes as feições defuntas. Depois, como se a morte espiritualizasse tudo, inclinou-se e beijou-a na testa. Foi nesse momento que Fortunato chegou à porta. Estacou assombrado; não podia ser o beijo da amizade, podia ser o epílogo de um livro adúltero [...]. Entretanto, Garcia inclinou-se ainda para beijar outra vez o cadáver, mas então não pôde mais. O beijo rebentou em soluços, e os olhos não puderam conter as lágrimas, que vieram em borbotões, lágrimas de amor calado, e irremediável desespero. Fortunato, à porta, onde ficara, saboreou tranquilo essa explosão de dor moral que foi longa, muito longa, deliciosamente longa.<br>\r\n\r\nASSIS, M. A causa secreta. \r\nDisponível em: www.dominiopublico.gov.br.\r\nAcesso em: 9 out. 2015.<br>\r\n\r\nNo fragmento, o narrador adota um ponto de vista que acompanha a perspectiva de Fortunato. O que singulariza esse procedimento narrativo é o registro do(a)<br>', '2018-10-29', NULL, 'd)'),
(NULL, 1999, 'vesti-lar', 'Língua Portuguesa ', 'Mas assim que penetramos no universo da web, descobrimos que ele constitui não apenas um imenso “território” em expansão acelerada, mas que também oferece inúmeros “mapas”, filtros, seleções para ajudar o navegante a orientar-se. O melhor guia para a web é a própria web. Ainda que seja preciso ter a paciência de explorá-la. Ainda que seja preciso arriscar-se a ficar perdido, aceitar “a perda de tempo” para familiarizar-se com esta terra estranha. Talvez seja preciso ceder por um instante a seu aspecto lúdico para descobrir, no desvio de um link, os sites que mais se aproximam de nossos interesses profissionais ou de nossas paixões e que poderão, portanto, alimentar da melhor maneira possível nossa jornada pessoal.<br>\r\n\r\nO usuário iniciante sente-se não raramente desorientado no oceano de informações e possibilidades disponíveis na rede mundial de computadores. Nesse sentido, Pierre Lévy destaca como um dos principais aspectos da internet o(a)<br>', '2018-10-29', NULL, ''),
(NULL, 1994, 'vesti-lar', 'Língua Portuguesa ', 'Essas moças tinham o vezo de afirmar o contrário do que desejavam. Notei a singularidade quando principiaram a elogiar o meu paletó cor de macaco.\r\nExaminavam-no sérias, achavam o pano e os aviamentos de qualidade superior, o feitio admirável. Envaideci-me: nunca havia reparado em tais vantagens. Mas os gabos se prolongaram, trouxeram-me desconfiança. Percebi afinal que elas zombavam e não me susceptibilizei. Longe disso: achei curiosa aquela maneira de falar pelo avesso, diferente das grosserias a que me habituara. Em geral me diziam com franqueza que a roupa não me assentava no corpo, sobrava nos sovacos.<br>\r\n\r\nPor meio de recursos linguísticos, os textos mobilizam estratégias para introduzir e retomar ideias, promovendo a progressão do tema. No fragmento transcrito, um novo aspecto do tema é introduzido pela expressão<br>', '2018-10-29', NULL, ''),
(NULL, 1998, 'vesti-lar', 'Língua Portuguesa ', 'O exame dos textos e mensagens de Propaganda revela que ela apresenta posições parciais que refletem apenas o pensamento de uma minoria, como se exprimissem, em vez disso, a convicção de uma população; trata-se, no fundo, de convencer o ouvinte ou o leitor de que, em termos de opinião, está fora do caminho certo, e de induzi-lo a aderir às teses que lhes são apresentadas, por um mecanismo bem conhecido da psicologia social, o do conformismo induzido por pressões do grupo sobre o indivíduo isolado.<br>\r\n\r\nDe acordo com o texto, as estratégias argumentativas e o uso da linguagem na produção da propaganda favorecem a<br>', '2018-10-29', NULL, ''),
(NULL, 2009, 'vesti-lar', 'Língua Portuguesa', 'E aqui, antes de continuar este espetáculo, é necessário que façamos uma advertência a todos e a cada um. Neste momento, achamos fundamental que cada um tome uma posição definitiva. Sem que cada um tome uma posição definitiva, não é possível continuarmos. É fundamental que cada um tome uma posição, seja para a esquerda, seja para a direita. Admitimos mesmo que alguns tomem uma posição neutra, fiquem de braços cruzados. Mas é preciso que cada um, uma vez tomada sua posição, fique nela! Porque senão, companheiros, as cadeiras do teatro rangem muito e ninguém ouve nada.<br>\r\n\r\nA peça Liberdade, liberdade, encenada em 1964, apresenta o impasse vivido pela sociedade brasileira em face do regime vigente. Esse impasse é representado no fragmento pelo(a)<br>', '2018-10-29', NULL, ''),
(NULL, 2014, 'vesti-lar', 'Língua Portuguesa ', 'Nuances\r\n\r\nEuforia: alegria barulhenta.<br> Felicidade: alegria silenciosa.<br>\r\nGravar: quando o ator é de televisão.<br> Filmar: quando ele quer deixar claro que não é de televisão.<br>\r\nGrávida: em qualquer ocasião.<br> Gestante: em filas e assentos preferenciais.<br>\r\n\r\nGuardar: na gaveta.<br>\r\nSalvar: no computador.<br>Salvaguardar: no Exército.<br>\r\n\r\nMenta: no sorvete, na bala ou no xarope.<br> Hortelã: na horta ou no suco de abacaxi.<br>\r\n Peça: quando você vai assistir.<br>Espetáculo: quando você está em cartaz com ele.<br>\r\n\r\nO texto trata da diferença de sentido entre vocábulos muito próximos. Essa diferença é apresentada considerando-se a(s)<br>\r\n\r\n', '2018-10-29', NULL, ''),
(NULL, 2013, 'vesti-lar', 'Língua Portuguesa', 'Sítio Gerimum<br>\r\nEste é o meu lugar [...]<br>\r\nMeu Gerimum é com g<br>\r\nVocê pode ter estranhado<br>\r\nGerimum em abundância<br>\r\nAqui era plantado<br>\r\nE com a letra g<br>\r\nMeu lugar foi registrado.<br>\r\n\r\nNos versos de um menino de 12 anos, o emprego da palavra “Gerimum” grafada com a letra “g” tem por objetivo\r\n', '2018-10-29', NULL, ''),
(NULL, 2013, 'vesti-lar', 'Língua Portuguesa ', 'Contranarciso<br>\r\nem mim<br>\r\neu vejo o outro<br>\r\ne outro<br>\r\ne outro<br>\r\nenfim dezenas<br>\r\ntrens passando<br>\r\nvagões cheios de gente<br>\r\ncentenas<br>\r\n<br>\r\no outro<br>\r\nque há em mim<br>\r\né você<br>\r\nvocê<br>\r\ne você<br>\r\n<br>\r\nassim como<br>\r\neu estou em você<br>\r\neu estou nele<br>\r\nem nós<br>\r\ne só quando<br>\r\nestamos em nós<br>\r\nestamos em paz<br>\r\nmesmo que estejamos a sós<br>\r\n\r\nA busca pela identidade constitui uma faceta da tradição literária, redimensionada pelo olhar contemporâneo. No poema, essa nova dimensão revela a<br>\r\n', '2018-10-29', NULL, ''),
(NULL, 2011, 'vesti-lar', 'Língua Portuguesa', 'João/Zero(Wagner Moura) é um cientista genial, mas infeliz porque há 20 anos atrás foi humilhado publicamente durante uma festa e perdeu Helena (Alinne Moraes), uma antiga e eterna paixão. Certo dia, uma experiência com um de seus inventos permite que ele faça uma viagem no tempo, retornando para aquela época e podendo interferir no seu destino. Mas quando ele retorna, descobre que sua vida mudou totalmente e agora precisa encontrar um jeito de mudar essa história, nem que para isso tenha que voltar novamente ao passado. Será que ele conseguirá acertar as coisas?<br>\r\n\r\nQual aspecto da organização gramatical atualiza os eventos apresentados na resenha, contribuindo para despertar o interesse do leitor pelo filme?<br>', '2018-10-29', NULL, ''),
(NULL, 1995, 'vesti-lar', 'Língua Portuguesa ', 'O homem disse, Está a chover, e depois, Quem é você, Não sou daqui, Anda à procura de comida, Sim, há quatro dias que não comemos, E como sabe que são quatro dias, É um cálculo, Está sozinha, Estou com o meu marido e uns companheiros, Quantos são, Ao todo, sete, Se estão a pensar em ficar conosco, tirem daí o sentido, já somos muitos, Só estamos de passagem, Donde vêm, Estivemos internados desde que a cegueira começou, Ah, sim, a quarentena, não serviu de nada, Por que diz isso, Deixaram-nos sair, Houve um incêndio e nesse momento percebemos que os soldados que nos vigiavam tinham desaparecido, E saíram, Sim, Os vossos soldados devem ter sido dos últimos a cegar, toda a gente está cega, Toda a gente, a cidade toda, o país...<br>\r\n\r\nA cena retrata as experiências das personagens em um país atingido por uma epidemia. No diálogo, a violação de determinadas regras de pontuação<br>', '2018-10-29', NULL, ''),
(NULL, 2018, 'vesti-lar', 'Matemática', 'Às 17 h 15 min começa uma forte chuva, que cai com intensidade constante. Uma piscina em forma de um paralelepípedo retângulo, que se encontrava inicialmente vazia, começa a acumular a água da chuva e, às 18 horas, o nível da água em seu interior alcança 20 cm de altura. Nesse instante, é aberto o registro que libera o escoamento da água por um ralo localizado no fundo dessa piscina, cuja a vazão é constante. Às 18 h 40 min a chuva cessa e, nesse exato instante, o nível da água na piscina baixou para 15 cm.\r\n\r\nO instante em que a água dessa piscina terminar de escoar completamente está compreendida entre?\r\n', '2018-10-30', NULL, ''),
(NULL, 2018, 'vesti-lar', 'Matemática', 'Um morador de uma região metropolitana tem 50% de probabilidade de atrasar-se para o trabalho quando chove na região; caso não chova, sua probabilidade de atraso é de 25%. Para um determinado dia. O serviço de meteorologia estima em 30% a probabilidade da ocorrência de chuva nessa região.\r\n\r\nQual é a probabilidade de esse morador se atrasar para o\r\nserviço no dia para o qual foi dada a estimativa de chuva?\r\n\r\n', '2018-10-30', NULL, ''),
(NULL, 2019, 'vesti-lar', 'Matemática', 'Em uma de suas viagens, um turista comprou uma lembrança de um dos monumentos que visitou. Na base do objeto há informações dizendo que se trata de uma peça em escala 1 : 400, e que seu volume é de 25 cm3.\r\n\r\nO volume do monumento original, em metro cúbico, é de...\r\n', '2018-10-30', NULL, ''),
(NULL, 2019, 'vesti-lar', 'Matemática', 'Uma empresa especializada em conservação de piscinas utiliza um produto para tratamento da água cujas especificações técnicas sugerem que seja adicionado 1,5 mL desse produto para cada 1 000 L de água da piscina. Essa empresa foi contratada para cuidar de uma piscina de base retangular, de profundidade constante igual a 1,7 m, com largura e comprimento iguais a 3 m\r\ne 5 m, respectivamente. O nível da lâmina d’água dessa piscina é mantido a 50 cm da borda da piscina.\r\n\r\nA quantidade desse produto, em mililitro, que deve ser adicionada a essa piscina de modo a atender às suas especificações técnicas é?\r\n', '2018-10-30', NULL, ''),
(NULL, 2018, 'vesti-lar', 'Matemática', 'Em um teleférico turístico, bondinhos saem de estações ao nível do mar e do topo de uma montanha. A travessia dura 1,5 minuto e ambos os bondinhos se\r\ndeslocam à mesma velocidade. Quarenta segundos após o bondinho A partir da estação ao nível do mar, ele cruza com o bondinho B, que havia saído do topo da montanha.\r\n\r\nQuantos segundos após a partida do bondinho B partiu o\r\nbondinho A?\r\n', '2018-10-30', NULL, ''),
(NULL, 2019, 'vesti-lar', 'Matemática', 'Em uma cantina. P sucesso de venda no verão são sucos preparados à base de polpa de frutas. Um dos sucos mais vendidos é o de morango com acerola, que é preparado com 2/3 de polpa de morango e 1/3 de polpa de acerola.\r\n\r\nPara o comerciante, as polpas são vendidas em embalagens de igual volume. Atualmente, a embalagem da polpa de morango custa R$ 18,00 e a de acerola,\r\nR$ 14,70. Porém, está prevista uma alta no preço da embalagem da polpa de acerola no próximo mês, passando a custar R$ 15,30.\r\n\r\nPara não aumentar o preço do suco, o comerciante negociou com o fornecedor uma redução no preço da embalagem da polpa de morango.\r\n\r\nA redução, em real, no preço da embalagem da polpa morango deverá ser de?\r\n', '2018-10-30', NULL, ''),
(NULL, 2018, 'vesti-lar', 'Matemática', 'Um casal realiza sua mudança de domicílio e necessita colocar numa caixa de papelão um objeto cúbico, de 80 cm de aresta, que não pode ser desmontado. Eles têm à disposição cinco caixas, com diferentes dimensões, conforme descrito: \r\n\r\n Caixa 1: 86 cm x 86 cm x 86 cm\r\n Caixa 2: 75 cm x 82 cm x 90 cm\r\n Caixa 3: 85 cm x 82 cm x 90 cm\r\n Caixa 4: 82 cm x 95 cm x 82 cm\r\n Caixa 5: 80 cm x 95 cm x 85 cm\r\n\r\nO casal precisa escolher uma caixa na qual o objeto caiba, de modo que sobre o menor espaço livre em seu interior.\r\n\r\nA caixa escolhida pelo casal deve ser a de número\r\n', '2018-10-30', NULL, ''),
(NULL, 2012, 'vesti-lar', 'Matemática', 'A mensagem digitada no celular, enquanto você dirige, tira sua concentração e, por isso, dever ser evitada. Pesquisas mostram que um motorista que dirige um carro a uma velocidade constante percorre “às cegas” (isto é, sem ter visão da pista) uma distância proporcional ao tempo gasto ao olhar para o celular durante a digitação da mensagem. Considere que isso de fato aconteça.\r\nSuponha que dois motoristas (X e Y) dirigem com a mesma velocidade constante e digitam a mesma mensagem em seus celulares. Suponha, ainda, que o tempo gasto pelo motorista X olhando para seu celular enquanto digita a mensagem corresponde a 25% do tempo gasto pelo motorista Y para executar a mesma tarefa.\r\n\r\n\r\nA razão entre as distâncias percorridas ás cegas por X e Y, nessa ordem, é igual a?\r\n', '2018-10-30', NULL, ''),
(NULL, 2015, 'vesti-lar', 'Matemática', 'Para uma temporada das corridas de Fórmula 1, a capacidade do tanque de combustível de cada carro passou a ser de 100 kg de gasolina. Uma equipe\r\noptou por utilizar uma gasolina com densidade de 750 gramas por litro, iniciando a corrida com o tanque cheio. Na primeira parada de reabastecimento, um carro dessa equipe apresentou um registro em seu computador de bordo acusando o consumo de quatro décimos da gasolina\r\noriginalmente existente no tanque. Para minimizar o peso desse carro e garantir o término da corrida, a equipe de apoio reabasteceu o carro com a terça parte do que restou no tanque na chegada ao reabastecimento.\r\n\r\n\r\nA quantidade de gasolina utilizada, em litro, no reabastecimento foi\r\n', '2018-10-30', NULL, ''),
(NULL, 2013, 'vesti-lar', 'Matemática', 'A energia solar vai abastecer parte da demanda de energia do campus de uma universidade brasileira. A instalação de painéis solares na área dos estacionamentos e na cobertura do hospital pediátrico será aproveitada nas instalações universitárias e também ligada na rede da companhia elétrica distribuidora de energia.\r\nO projeto inclui 100 m² de painéis solares que ficarão instalados nos estacionamentos, produzindo energia elétrica e proporcionando sombra para os carros. Sobre o hospital pediátrico serão colocados aproximadamente 300 m² painéis, sendo 100 m² para gerar energia elétrica utilizada no\r\nCampus, e 200 m² para geração de energia térmica, produzindo aquecimento de água utilizada nas caldeiras do hospital.\r\nSuponha que cada metro quadrado de painel solar para energia elétrica gere uma economia de 1kWh por dia e cada metro quadrado produzindo energia térmica permita economizar 0,7 kWh por dia para a universidade. Em uma segunda fase do projeto, será aumentada em 75% a área coberta pelos painéis solares que geram energia elétrica. Nessa fase também deverá ser ampliada a área de cobertura com painéis para geração de energia térmica. \r\n\r\n\r\nPara se obter o dobro da quantidade de energia economizada diariamente, em relação à primeira fase, a área total dos painéis que geram energia térmica, em\r\nmetro quadrado, deverá ter o valor mais próximo de\r\n', '2018-10-30', NULL, ''),
(NULL, 2008, 'vesti-lar', 'História', 'No império africano do Mali, no século XIV, Tombuctu foi centro de um comércio internacional onde tudo era negociado — sal, escravos, marfim etc. Havia também um grande comércio de livros de história, medicina, astronomia e matemática, além de grande concentração\r\nde estudantes. A importância cultural de Tombuctu pode ser percebida por meio de um velho provérbio: “O sal vem do norte, o ouro vem do sul, mas as palavras de Deus e\r\nos tesouros da sabedoria vêm de Tombuctu”.\r\n\r\n\r\nUma explicação para o dinamismo dessa cidade e sua\r\nimportância histórica no período mencionado era o(a)\r\n', '2018-10-30', NULL, ''),
(NULL, 1999, 'vesti-lar', 'História', 'Após a Declaração Universal dos Direitos Humanos pela ONU, em 1948, a Unesco publicou estudos de cientistas de todo o mundo que desqualificaram as doutrinas racistas e demonstraram a unidade do gênero humano. Desde então, a maioria dos próprios cientistas europeus passou a reconhecer o caráter discriminatório da pretensa superioridade racial do homem branco e a condenar as aberrações cometidas em seu nome.\r\n\r\n\r\nA posição assumida pela Unesco, a partir de 1948, foi\r\nmotivada por acontecimentos então recentes, dentre os\r\nquais se destacava o(a)\r\n', '2018-10-30', NULL, ''),
(NULL, 2007, 'vesti-lar', 'História', 'A primeira Guerra do Golfo, genuinamente apoiada\r\npelas Nações Unidas e pela comunidade internacional,\r\nassim como a reação imediata ao Onze de Setembro,\r\ndemonstravam a força da posição dos Estados Unidos na\r\nera pós-soviética.\r\n\r\n\r\n\r\nUm aspecto que explica a força dos Estados Unidos,\r\napontada pelo texto, reside no(a)\r\n', '2018-10-30', NULL, ''),
(NULL, 2012, 'vesti-lar', 'História', 'Palestinos se agruparam em frente a aparelhos de televisão e telas montadas ao ar livre em Ramalah, na Cisjordânia, para acompanhar o voto da resolução que pedia o reconhecimento da chamada Palestina como um Estado observador não membro da Organização das Nações Unidas (ONU). O objetivo era esperar pelo nascimento, ao menos formal, de um Estado palestino. Depois da aprovação da resolução, centenas de pessoas foram à praça da cidade com bandeiras palestinas, soltaram fogos de artificio, fizeram buzinações e dançaram pelas ruas. Aprovada com 138 votos dos 193 da Assembleia-Geral, a resolução eleva o status do Estado palestino perante a organização.\r\n\r\n\r\n\r\nA mencionada resolução da ONU referendou o(a)\r\n', '2018-10-30', NULL, ''),
(NULL, 1989, 'vesti-lar', 'História', 'Estão aí, como se sabe, dois candidatos à presidência, os senhores Eduardo Gomes e Eurico Dutra, e um terceiro, o senhor Getúlio Vargas, que deve ser candidato de algum grupo político oculto, mas é também o candidato popular.\r\nPorque há dois “queremos”: o “queremos” dos que querem ver se continuam nas posições e o “queremos” popular... afinal. O que é que o senhor Getúlio Vargas é? É fascista? É comunista? É ateu? É cristão? Quer sair? Quer ficar? O povo, entretanto, parece que gosta dele por isso mesmo, porque ele é “à moda da casa”.\r\n\r\n\r\nO movimento político mencionado no texto caracterizou-se\r\nPor\r\n', '2018-10-30', NULL, ''),
(NULL, 2011, 'vesti-lar', 'História', 'No período anterior ao golpe militar de 1964, os documentos episcopais indicavam para os bispos que o desenvolvimento econômico, e claramente o\r\ndesenvolvimento capitalista, orientando-se no sentido da justa distribuição da riqueza, resolveria o problema da miséria rural e, consequentemente, suprimiria a possibilidade do proselitismo e da expansão comunista entre os camponeses. Foi nesse sentido que o golpe de Estado, de 31 de março de 1964, foi acolhido pela igreja.\r\n\r\n\r\nEm que pesem as divergências no interior do clero após a instalação da ditadura civil-militar, o posicionamento mencionado no texto fundamentou-se no entendimento da hierarquia católica de que o(a)\r\n', '2018-10-30', 6, ''),
(NULL, 2006, 'vesti-lar', 'História', 'O conceito de democracia, no pensamento de Habermas, é construído a partir de uma dimensão procedimental, calcada no discurso e na deliberação.\r\nA legitimidade democrática exige que o processo de tomada de decisões políticas ocorra a partir de uma ampla discussão pública, para somente então decidir. Assim, o caráter deliberativo corresponde a um processo coletivo de ponderação e análise, permeado pelo discurso, que antecede a decisão.\r\n\r\n\r\nO conceito de democracia proposto por Jurgen Habernas pode favorecer processos de inclusão social. De acordo com o texto, é uma condição para que isso aconteça o(a)\r\n', '2018-10-30', 7, ''),
(NULL, 2012, 'vesti-lar', 'História', 'O instituto popular, de acordo com o exame da razão, fez da figura do alferes Xavier o principal dos inconfidentes, e colocou os seus parceiros a meia ração de glória. Merecem, decerto, a nossa estima aqueles outros;\r\neram patriotas. Mas o que se ofereceu a carregar com os pecadores de Israel, o que chorou de alegria quando viu comutada a pena de morte dos seus companheiros, pena que só ia ser executada nele, o enforcado, o esquartejado, o decapitado, esse tem de receber o prêmio na proporção do martírio, e ganhar por todos, visto que pagou por todos.\r\n\r\n\r\nNo processo de transição para a República, a narrativa machadiana sobre a Inconfidência Mineira associa\r\n', '2018-10-30', 8, ''),
(NULL, 2002, 'vesti-lar', 'História', 'A participação da mulher no processo de decisão política ainda é extremamente limitada em praticamente todos os países, independentemente do regime econômico e social e da estrutura institucional vigente em cada um deles. É fato público e notório, além de empiricamente comprovado, que as mulheres estão em geral sub-representadas nos órgãos do poder, pois a proporção não corresponde jamais ao peso relativo dessa parte da população.\r\n \r\n\r\nNo âmbito do Poder Legislativo brasileiro, a tentativa de\r\nreverter esse quadro de sub-representação tem envolvido\r\na implementação, pelo Estado, de\r\n', '2018-10-30', 9, ''),
(NULL, 2012, 'vesti-lar', 'Geografia', 'A configuração do espaço urbano da região do Entorno do Distrito Federal assemelha-se às demais aglomerações urbanas e regiões metropolitanas do país, onde é facilmente identificável a constituição de um centro dinâmico e desenvolvido, onde se concentram as oportunidades de trabalho e os principais serviços, e a constituição de uma região periférica concentradora de população de baixa renda, com acesso restrito às principais atividades com capacidade de acumulação e produtividade, e aos serviços sociais e infraestrutura básica.\r\n\r\n\r\nA organização interna do aglomerado urbano descrito é\r\nresultado da ocorrência do processo de\r\n', '2018-11-01', NULL, ''),
(NULL, 2013, 'vesti-lar', 'Geografia', 'México, Colômbia, Peru e Chile decidiram seguir um\r\ncaminho mais curto para a integração regional. Os quatro países, em meados de 2012, criaram a Aliançado Pacifico e eliminaram, em 2013, as tarifas aduaneiras de 90% do total de produtos comercializados entre suas fronteiras.\r\n\r\nO acordo descrito no texto teve como objetivo econômico\r\npara os países-membros\r\n', '2018-11-01', NULL, ''),
(NULL, 2005, 'vesti-lar', 'Geografia', 'Os maiores consumidores da infraestrutura logística para exportação no Brasil são produtos a granel, dentre os quais se destacam o minério de ferro, petróleo\r\ne seus derivados e a soja, que, por possuírem baixo valor agregado, e por serem movimentados em grandes volumes, necessitam de uma infraestrutura de grande porte e baixos custos. No caso da soja, a infraestrutura deixando muito a desejas, resultando em enormes filas de navios, caminhões e trens, que, por ficarem grande parte do tempo ociosos nas filas, têm seu custo majorado, onerando fortemente o exportador, afetando sua margem de lucro e ameaçando nossa competitividade internacional.\r\n\r\n\r\nNo contexto do início do século XXI, uma ação para solucionar os problemas logísticos da soja apresentados no texto seria a\r\nA isenção de impostos de transportes.\r\n', '2018-11-01', NULL, ''),
(NULL, 2012, 'vesti-lar', 'Geografia', 'A diversidade de atividades relacionadas ao setor terciário reforça a tendência mais geral de desindustrialização de muitos dos países desenvolvidos\r\nsem que estes, contudo, percam o comando da economia. Essa mudança implica nova divisão internacional do trabalho, que não é mais apoiada na clara segmentação setorial das atividades econômicas.\r\n\r\n\r\n\r\nNesse contexto, o fenômeno descrito tem como um de seus resultados a\r\n', '2018-11-01', NULL, ''),
(NULL, 2010, 'vesti-lar', 'Geografia', 'O terremoto de 8,8 na escala Richter que atingiu a costa oeste do Chile, em fevereiro, provocou mudanças significativas no mapa da região. Segundo uma análise preliminar, toda a cidade de Concepción se deslocou pelo menos três metros para o oeste. Buenos Aires moveu-se cerca de 2,5 centímetros para oeste, enquanto Santiago, mais próxima do local do evento, deslocou-se quase 30 centímetros para o oeste-sudoeste. As cidades de Valparaíso, no Chile, e Mendoza, na Argentina, também tiveram suas posições alteradas significativamente (13,4 centímetros e 8,8 centímetros, respectivamente).\r\n\r\n\r\nNo texto, destaca-se um tipo de evento geológico frequente em determinadas partes da superfície terrestre. Esses eventos estão concentrados em\r\n', '2018-11-01', NULL, ''),
(NULL, 2009, 'vesti-lar', 'Geografia', 'Com a Lei de Terras de 1850, o acesso à terra só passou a ser possível por meio da compra com pagamento em dinheiro. Isso limitava, ou mesmo praticamente impedia, o acesso à terra para os trabalhadores escravos que conquistavam a liberdade.\r\n\r\n\r\n\r\nO fato legal evidenciado no texto acentuou o processo de\r\n', '2018-11-01', NULL, ''),
(NULL, 2006, 'vesti-lar', 'Geografia', 'O desgaste acelerado sempre existirá se o agricultor não tiver o devido cuidado de combater as causas, relacionadas a vários processos, tais como:\r\nempobrecimento químico e lixiviação provocados pelo esgotamento causado pelas colheitas e pela lavagem vertical de nutrientes da água que se infiltra no solo, bem como pela retirada de elementos nutritivos com as colheitas. Os nutrientes retirados, quando não repostos, são comumente substituídos por elementos tóxicos, como, por exemplo, o alumínio.\r\n\r\n\r\nA dinâmica ambiental exemplificada no texto gera a seguinte consequência para o solo agricultável:\r\n', '2018-11-01', NULL, ''),
(NULL, 2011, 'vesti-lar', 'Geografia', 'A instalação de uma refinaria obedece a diversos fatores técnicos. Um dos mais importantes é a localização, que deve ser próxima tanto dos centros\r\nde consumo como das áreas de produção. A Petrobras possui refinarias estrategicamente distribuídas pelo país. Elas são responsáveis pelo processamento de milhões de barris de petróleo por dia, suprindo o mercado com derivados que podem ser obtidos a partir de petróleo\r\nnacional ou importado.\r\n\r\n\r\nA territorialização de uma unidade produtiva depende de diversos fatores locacionais. A partir da leitura do texto, o fator determinante para a instalação das refinarias de petróleo é a proximidade a\r\n', '2018-11-01', NULL, ''),
(NULL, 2008, 'vesti-lar', 'Geografia', 'Ao destruir uma paisagem de árvores de troncos retorcidos, folhas e arbustos ásperos sobre os solos ácidos, não raro laterizados ou tomados pelas formas bizarras dos cupinzeiros, essa modernização lineariza e aparentemente não permite que se questione a pretensão modernista de que a forma deve seguir a função.\r\n\r\n\r\n\r\nO processo descrito ocorre em uma área biogeográfica com predomínio de vegetação\r\n', '2018-11-01', NULL, ''),
(NULL, 2018, 'vesti-lar', 'Geografia', 'Trata-se da perda progressiva da produtividade de biomas inteiros, afetando parcelas muito expressivas dos domínios subúmidos e semiáridos em todas as regiões quentes do mundo. É nessas áreas, ecologicamente transicionais, que a pressão sobre a biomassa se faz sentir com muita força, devido a retirada da cobertura florestal, ao superpastoreio e às atividades mineradoras não controladas, desencadeando um quadro agudo de degradação ambiental, refletido pela incapacidade de suporte para o desenvolvimento de espécies vegetais, seja uma floresta natural ou plantações agrícolas.\r\n\r\n\r\nO texto enfatiza uma consequência da relação entre a sociedade humana e o ambiente, que diz respeito ao processo de\r\n', '2018-11-01', NULL, ''),
(NULL, 2018, 'vesti-lar', 'Biologia', 'A terapia celular tem sido amplamente divulgada como revolucionária, por permitir a regeneração de tecidos a partir de células novas. Entretanto, a técnica de se introduzirem novas células em um tecido, para o tratamento de enfermidades em indivíduos, já era aplicada rotineiramente em hospitais.\r\n\r\nA que técnica refere-se o texto?\r\n', '2018-11-01', NULL, ''),
(NULL, 2012, 'vesti-lar', 'Biologia', 'A retina é um tecido sensível à luz, localizado na parte posterior do olho, onde ocorre o processo de formação de imagem. Nesse tecido, encontram-se vários tipos celulares específicos. Um desses tipos celulares são os cones, os quais convertem os diferentes comprimentos de onda da luz visível em sinais elétricos, que são transmitidos pelo nervo óptico até o cérebro.\r\n\r\n\r\n\r\nEm relação à visão, a degeneração desse tipo celular irá\r\n', '2018-11-01', NULL, ''),
(NULL, 2013, 'vesti-lar', 'Biologia', 'A Mata Atlântica caracteriza-se por uma grande diversidade de epífitas, como as bromélias. Essas plantas estão adaptadas a esse ecossistema e conseguem captar luz, água e nutrientes mesmo vivendo sobre as árvores.\r\n\r\n\r\n\r\nEssas espécies captam água do(a)\r\n', '2018-11-01', NULL, '');